import {ElapsedTimeFriendly} from "./ElapsedTimeFriendly";
import {ElapsedTimeLiveLong} from "./ElapsedTimeLiveLong";
import {ElapsedTimeLiveShort} from "./ElapsedTimeLiveShort";
import {ElapsedTime} from "./ElapsedTime";
import {DateDDMMMYY} from "./DateDDMMMYY";
import {DateDashedDDMMYYYY} from "./DateDD-MM-YYYY";
import {DateDashedDDMMMYYYY} from "./DateDD-MMM-YYYY";
import {DateDashedMMDDYYYY} from "./DateMM-DD-YYYY";
import {DateTimeDDMMMYYHHMM} from "./DateTimeDDMMMYYHHMM";
import {BooleanIcon} from "./BooleanIcon";
import {StatusIcon} from "./StatusIcon";
import {LookupValue} from "./LookupValue";
import {EpochDateDDMMMYY} from "./EpochDateDDMMMYY";
import {EpochDateTimeDDMMMYYHHMM} from "./EpochDateTimeDDMMMYYHHMM";
import {PercentProgressBar} from "./PercentProgressBar";
import {Hyperlink} from "./Hyperlink";
import {ThumbNail} from "./ThumbNail";
import {DollarValue} from "./DollarValue";
import {TableRowStyler} from "./TableRowStyler";
import {HoverBox} from "./HoverBox";
import {VoteUp} from "./VoteUp";
import {Ranking} from "./Ranking";
import {IntYesNo} from "./IntYesNo";
import {IntActiveInactive} from "./IntActiveInactive";
import {DateLocale} from "./DateLocale";
import {DateTimeLocale} from "./DateTimeLocale";
import {TwoDecimal} from "./TwoDecimal";

declare const manywho: any;
class TableColumnComponents {

}

manywho.component.register('ElapsedTimeFriendly', ElapsedTimeFriendly);
manywho.component.register('ElapsedTimeLiveLong', ElapsedTimeLiveLong);
manywho.component.register('ElapsedTimeLiveShort', ElapsedTimeLiveShort);
manywho.component.register('ElapsedTime', ElapsedTime);
manywho.component.register('DateDDMMMYY', DateDDMMMYY);
manywho.component.register('DateDashedDDMMYYYY', DateDashedDDMMYYYY);
manywho.component.register('DateDashedDDMMMYYYY', DateDashedDDMMMYYYY);
manywho.component.register('DateDashedMMDDYYYY', DateDashedMMDDYYYY);
manywho.component.register('DateTimeDDMMMYYHHMM', DateTimeDDMMMYYHHMM);
manywho.component.register('BooleanIcon', BooleanIcon);
manywho.component.register('StatusIcon', StatusIcon);
manywho.component.register('LookupValue', LookupValue);
manywho.component.register('EpochDateDDMMMYY', EpochDateDDMMMYY);
manywho.component.register('EpochDateTimeDDMMMYYHHMM', EpochDateTimeDDMMMYYHHMM);
manywho.component.register('PercentProgressBar', PercentProgressBar);
manywho.component.register('Hyperlink', Hyperlink);
manywho.component.register('ThumbNail', ThumbNail);
manywho.component.register('DollarValue', DollarValue);
manywho.component.register('TableRowStyler', TableRowStyler);
manywho.component.register('HoverBox', HoverBox);
manywho.component.register('VoteUp', VoteUp);
manywho.component.register('Ranking', Ranking);
manywho.component.register('IntYesNo', IntYesNo);
manywho.component.register('IntActiveInactive', IntActiveInactive);
manywho.component.register('DateLocale', DateLocale);
manywho.component.register('DateTimeLocale', DateTimeLocale);
manywho.component.register('TwoDecimal', TwoDecimal);
